version: 2.1

jobs:
  build:
    docker:
      - image: cypress/browsers:node14.16.0-chrome89-ff86
    steps:
      - checkout

      # Install dependencies
      - run:
          name: Install Node.js and dependencies
          command: |
            nvm install 14
            nvm use 14
            npm install

      # Start Cypress tests
      - run:
          name: Run Cypress tests
          command: |
            npx cypress run

workflows:
  version: 2
  build:
    jobs:
      - build
