version: 2.1

jobs:
  build:
    docker:
      - image: cypress/browsers:node14.16.0-chrome89-ff86
    steps:
      - checkout

      # Install dependencies
      - run:
          name: Install Node.js and dependencies
          command: |
            # Download and install Node.js
            curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.38.0/install.sh | bash
            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
            [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion
            nvm install 14
            nvm use 14
            npm install

      # Start Cypress tests
      - run:
          name: Run Cypress tests
          command: |
            npx cypress run

workflows:
  version: 2
  build:
    jobs:
      - build
