name: Cypress Tests

on:
  push:
    branches:
      - master 

jobs:
      
  cypress-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16.x # You can change the Node.js version as needed
      
      - name: Delete package-lock.json
        run: rm -f package-lock.json    
      - name: Update npm
        run: npm install

      
      
      

      - name: Checkout
        uses: actions/checkout@v3
    

      - name: Run Cypress tests
        run: npm run cy:run # Adjust the script name as per your package.json

      - name: Upload test results
        if: ${{ always() }}
        uses: actions/upload-artifact@v2
        with:
          name: cypress-results
          path: cypress/screenshots # Adjust to the location of your test results
          

      - name: Save screenshots and reports as artifacts
        if: ${{ always() }}
        uses: actions/upload-artifact@v2
        with:
          name: cypress-screenshots-reports
          path: cypress/screenshots # Adjust to the location of your screenshots and reports

      
      - name: Upload videos
        if: ${{ always() }}
        uses: actions/upload-artifact@v2
        with:
          name: cypress-videos
          path: cypress/videos
