name: Cypress Tests

on:
  push:
    branches:
      - master 

jobs:

  wireguard_example:
    runs-on: ubuntu-latest
    steps:
      - name: Establish VPN connection
        run: |
            sudo apt update
            sudo apt install -y openvpn openvpn-systemd-resolved
            echo "${{ secrets.VPN_CONFIG }}" > vpn-config.ovpn
            echo "${{ secrets.VPN_USERNAME }}" > vpn-credentials.txt
            echo "${{ secrets.VPN_PASSWORD }}" >> vpn-credentials.txt
            sudo openvpn --config vpn-config.ovpn --auth-user-pass vpn-credentials.txt --daemon
            sleep 15
      
  cypress-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14 # You can change the Node.js version as needed

      - name: Install dependencies
        run: npm install # Or use yarn if preferred

      - name: Checkout
        uses: actions/checkout@v3
      - name: Install OpenVPN
        run: |
          sudo apt update
          sudo apt install -y openvpn openvpn-systemd-resolved
      - name: Connect to VPN
        uses: "kota65535/github-openvpn-connect-action@v2"
        with:
          config_file: .github/workflows/client.ovpn
          username: ${{ secrets.OVPN_USERNAME }}
          password: ${{ secrets.OVPN_PASSWORD }}
          client_key: ${{ secrets.USER_KEY }}

      - name: Run Cypress tests
        run: npm run cy:run # Adjust the script name as per your package.json

      - name: Upload test results
        if: ${{ always() }}
        uses: actions/upload-artifact@v2
        with:
          name: cypress-results
          path: cypress/screenshots # Adjust to the location of your test results
          

      - name: Save screenshots and reports as artifacts
        if: ${{ always() }}
        uses: actions/upload-artifact@v2
        with:
          name: cypress-screenshots-reports
          path: cypress/screenshots # Adjust to the location of your screenshots and reports

      
      - name: Upload videos
        if: ${{ always() }}
        uses: actions/upload-artifact@v2
        with:
          name: cypress-videos
          path: cypress/videos
